Checking in all backup stuff

diff --git a/container-backup b/container-backup
--- a/container-backup
+++ b/container-backup
@@ -1,91 +1,115 @@
 #!/bin/sh
 #
-# container-backup
-#
-# Controller script for container wide back-up
+# container-backup: Controller script for container wide back-up
 
 # Load all the fetures in the backup drop-in directory
-BACKUP_CONFIG="/etc/container/backup.d"
+# BACKUP_CONFIG="/etc/container/backup.d"
+#
+# BACKUP_LEGACY="/etc/container/backup.fnc"
+
+# Dumb drop-in function... removing
+# if [ -d $BACKUP_CONFIG ] ; then
+#  for feature in $BACKUP_CONFIG/* ; do
+#   if [ -r "$feature" ] ; then
+#    echo "[ INFO]: Loading feature($feature)."
+#    source "$feature"
+#   fi
+#  done
+# else
+#  if [ -f $BACKUP_LEGACY ] ; then
+#   echo "[ INFO]: Loading legacy feature($BACKUP_LEGACY)."
+#   source $BACKUP_LEGACY
+#  else
+#   echo "[ERROR]: Unable to load the drop-in directory($BACKUP_CONFIG) or function file($BACKUP_LEGACY)"
+#   return 10
+#  fi
+# fi
+
 BACKUP_FUNCTION="container_backup"
-BACKUP_LEGACY="/etc/container/backup.fnc"
-
-if [ -d $BACKUP_CONFIG ] ; then
- for feature in $BACKUP_CONFIG/* ; do
-  if [ -r "$feature" ] ; then
-   echo "[ INFO]: Loading feature($feature)."
-   source "$feature"
-  fi
- done
-else
- if [ -f $BACKUP_LEGACY ] ; then
-  echo "[ INFO]: Loading legacy feature($BACKUP_LEGACY)."
-  source $BACKUP_LEGACY
- else
-  echo "[ERROR]: Unable to load the drop-in directory($BACKUP_CONFIG) or function file($BACKUP_LEGACY)"
-  return 10
- fi
-fi
-
+# Load backup definition
+. /etc/container/backup
 if [ "$(type -t $BACKUP_FUNCTION)" == "$BACKUP_FUNCTION" ] ; then
  echo "[ INFO]: Backup function($BACKUP_FUNCTION) loaded."
 else
  echo "[ERROR]: Unable to find the backup function($BACKUP_FUNCTION)"
- echo 11
+ return 1
 fi
 
-# Load the encryption key
-LEGACY_KEY="/etc/container/keys/backup.key"
-ENCRYPTION_KEY="/etc/container/keys.d/backup-encryption.key"
+# Load and/or confirm the key is loaded
+BACKUP_KEY="/etc/container/backup.key"
 
-if [ -r $ENCRYPTION_KEY ] ; then
- echo "[ INFO]: Default encryption key($ENCRYPTION_KEY)"
+if [ ! -f $BACKUP_KEY ] ; then
+ echo "[ERROR] Unable to find the backup key($BACKUP_KEY)"
+ return 2
 else
- if [ -r $LEGACY_KEY ] ; then
-  echo "[ WARN]: Overwrite Encryption Key with Legacy Key($LEGACY_KEY)"
-  ENCRYPTION_KEY=$LEGACY_KEY
- else
-  echo "[ERROR]: Could not find Encryption Key($ENCROPTION_KEY) or Legacy Key($LEGACY_KEY)"
-  return 30
+ if  [ -L $TARGET ] ; then
+  if [ ! -e $TARGET ] ; then # Symlink is not correct
+   echo "[ERROR] Unable to find backup key target"
+   return 3
+  fi
  fi
 fi
-KEY_FINGERPRINT="$(gpg --show-keys $ENCRYPTION_KEY | sed -n '2p' | xargs)"
-if [ "" == "$(gpg --list-keys)" ] ; then
- gpg --trusted-key $KEY_FINGERPRINT --import $ENCRYPTION_KEY
+
+KEY_FINGERPRINT="$(/usr/bin/gpg --show-keys $BACKUP_KEY | sed -n '2p' | xargs)"
+if [ "" == "$(/usr/bin/gpg --list-keys)" ] ; then
+ /usr/bin/gpg --trusted-key $KEY_FINGERPRINT --import $ENCRYPTION_KEY
 else
- gpg --list-keys
+ /usr/bin/gpg --list-keys
 fi
  # gpg --trusted-key $(gpg --show-keys /etc/backup/config/encryption.key | sed -n '2p' | xargs) --import /etc/backup/config/encryption.key
+
+
+
+# if [ -r $ENCRYPTION_KEY ] ; then
+#  echo "[ INFO]: Default encryption key($ENCRYPTION_KEY)"
+# else
+#  if [ -r $LEGACY_KEY ] ; then
+#   echo "[ WARN]: Overwrite Encryption Key with Legacy Key($LEGACY_KEY)"
+#   ENCRYPTION_KEY=$LEGACY_KEY
+#  else
+#   echo "[ERROR]: Could not find Encryption Key($ENCROPTION_KEY) or Legacy Key($LEGACY_KEY)"
+#   return 30
+#  fi
+# fi
  
 # Execute backup
 BACKUP_TAG="$(date --utc +%H)"
-FOLDER_WORKING="/tmp/backup"
+# FOLDER_WORKING="/tmp/backup"
+FOLDER_WORK="/tmp/backup"
 FOLDER_CACHE="/var/backup"
-FOLDER_BACKUP="/opt/backup"
+# FOLDER_BACKUP="/opt/backup"
+FOLDER_DEST="/mnt/volumes/backup"
+FILE_MANIFEST=$FOLDER_DEST/duplicity-full.*.manifest.gpg
 
-echo "[ INFO]: Execute the container backup function"
-cd $FOLDER_WORKING
-container_backup
-if [ ! $? -eq 0 ] ; then
- echo "[ERROR]: Function did not work"
- return 1
+# Collect backup material
+/bin/mkdir -p $FOLDER_WORK
+if [ ! -d $FOLDER_WORK] ; then
+ echo "[ INFO]: Execute the container backup function"
+ cd $FOLDER_WORK
+ container_backup # Call backup function
+ RTN=$?
+ if [ $RTN -ne 0 ] ; then
+  echo "[ERROR]: Function($RTN) did not work"
+  return $RTN
+ fi
 fi
 cd /
 
+
 # Clear all but the latest chain
 echo "[ INFO]: Clean up backups"
-duplicity remove-all-but-n-full 1 --force file://$FOLDER_BACKUP
+/usr/bin/duplicity remove-all-but-n-full 1 --force file://$FOLDER_DEST
 
-FILE_MANIFEST=$FOLDER_BACKUP/duplicity-full.*.manifest.gpg
-# SET BACKUP CHAIN
+# Backup $FOLDER_WORK -> $FOLDER_CACHE -> $FOLDER_DEST
+# Determine if full or incremental
 if [ ! -f $FILE_MANIFEST ] ; then
  echo "[ INFO]: FULL backup(File)"
- 
- duplicity full --encrypt-key $KEY_FINGERPRINT --archive-dir $FOLDER_CACHE $FOLDER_WORKING file://$FOLDER_BACKUP
+ /usr/bin/duplicity full --encrypt-key $KEY_FINGERPRINT --archive-dir $FOLDER_CACHE $FOLDER_WORK file://$FOLDER_DEST
 else
    # RESET BACKUP CHAIN - At midnight
  if [ "00" == "$(date --utc +%H)" ] ; then
   echo "[ INFO]: FULL backup(00)"
-  duplicity full --encrypt-key $KEY_FINGERPRINT --archive-dir $FOLDER_CACHE $FOLDER_WORKING file://$FOLDER_BACKUP
+  /usr/bin/duplicity full --encrypt-key $KEY_FINGERPRINT --archive-dir $FOLDER_CACHE $FOLDER_WORK file://$FOLDER_DEST
  else
   TIMESTAMP_LAST=$(date --utc +%s -r $FILE_MANIFEST)
   TIMESTAMP_NOW=$(date --utc +%s)
@@ -94,12 +118,12 @@ else
   # RESET BACKUP CHAIN - If older than 24 hours
   if [ $TIMESTAMP_DAY -lt $TIMESTAMP_DELTA ] ; then
    echo "[ INFO]: FULL backup(Timestamp)"
-   duplicity full --encrypt-key $KEY_FINGERPRINT --archive-dir $FOLDER_CACHE $FOLDER_WORKING file://$FOLDER_BACKUP
+     /usr/bin/duplicity full --encrypt-key $KEY_FINGERPRINT --archive-dir $FOLDER_CACHE $FOLDER_WORK file://$FOLDER_DEST
   else # INCREMENTAL BACKUP
    echo "[ INFO]: INCREMENTAL backup"
-   duplicity incr --encrypt-key $KEY_FINGERPRINT --archive-dir $FOLDER_CACHE $FOLDER_WORKING file://$FOLDER_BACKUP
+   duplicity incr --encrypt-key $KEY_FINGERPRINT --archive-dir $FOLDER_CACHE $FOLDER_WORK file://$FOLDER_DEST
   fi
  fi
 fi
-echo "[ INFO]: Clean working folder $FOLDER_WORKING"
-rm -rvf $FOLDER_WORKING/*
+echo "[ INFO]: Clean working folder $FOLDER_WORK"
+rm -rvf $FOLDER_WORK/*
diff --git a/health-check b/health-check
--- a/health-check
+++ b/health-check
@@ -1,10 +1,11 @@
 #!/bin/sh
 #
-# health-check: This is the default status check. Unless overridden all status checks
-#               [health|liveness|readiness|startup] should end up here. This script 
-#               should be overidden by downstream containers or by providing a volume 
-#               that has `status-check` script.  This script will return a 1 by default
-#               if the script is not found.
+# health-check: This is the default health check. All checks should default to
+#               script.  This script attempts to call the base status check at
+#               `/etc/container/status-check` and optionally tries to call
+#               `/mnt/volumes/container/status-check` if the file exists to allow for
+#               runtime checks to be defined.  Runtime status-check should only be used in
+#               development.
 # 
 # author: adam@gautier.org
 # date: 2022-11-16
@@ -12,16 +13,20 @@
 #
 # - - - - - - - - - - - - - - - - - - - - - - -
 
-DEFAULT_STATUS_CHECK="/mnt/volumes/container/status-check"
+STATUS_CHECK="/etc/container/status-check"
 
-if [ ! -f $DEFAULT_STATUS_CHECK ] ; then
- echo "[ERROR] Unable to find default status check($DEFAULT_STATUS_CHECK) script"
+if [ ! -f $STATUS_CHECK ] ; then
+ echo "[ERROR] Unable to find default status check($STATUS_CHECK) script"
  return 1
 fi
 
-exec $DEFAULT_STATUS_CHECK
+exec $STATUS_CHECK
 RTN=$?
 if [ $RTN -ne 0 ] ; then
- echo "[ERROR] Invalid status($RTN) check($DEFAULT_STATUS_CHECK)"
+ return $RTN
 fi
-return $RTN
+
+RUNTIME_STATUS_CHECK="/mnt/volumes/container/status-check"
+
+exec $RUNTIME_STATUS_CHECK
+return $?
